import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "@/core/components/dashboard/sidebar/sidebar";
import { Navbar } from "@/core/components/dashboard/navbar";
import AuthWrapper from "@/core/components/providers/AuthWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthWrapper>
          <main className="h-full">
            <Sidebar />
            <div className="pl-[60px] h-full">
              <div className="flex h-full">
                {/* Separator */}
                <div className="border-l border-gray-300 h-full" />
                <div className="h-full flex-1">
                  <Navbar />
                  {children}
                </div>
              </div>
            </div>
          </main>
        </AuthWrapper>
      </body>
    </html>
  );
}
